FROM openjdk:17-alpine
ARG JAR_FILE=/api-server-java/build/libs/api-server-java-0.0.1-SNAPSHOT.jar

COPY ./api-server-java /api-server-java
WORKDIR /api-server-java

RUN ./gradlew clean build -x test \
    && cp ${JAR_FILE} app.jar

# sudo docker exec -it innovation-java-server /bin/sh
# java -jar app.jar

ENV TZ Asia/Seoul

ENTRYPOINT ["java","-jar","app.jar"]
